noq_django/backend/scripts/generate_data.py

Uppdaterat generate scripted för bättre frontend tester

updated generate data script to ensure departures are generated

---

noq_django/noq_django/api/api_schemas.py
noq_django/noq_django/api/user_api.py

Relaterat till [#364](https://github.com/noQ-sweden/noq/issues/364) och [#279](https://github.com/noQ-sweden/noq/issues/279)

Added api for listing available products and sending a booking request

---

noq_django/backend/scripts/generate_data.py

This change fixes issue when the test data is generated again and the script tries to save the test user/host to a unique field in the database.

Adds check to control it the test user is already created in the DB

---

noq_django/backend/forms.py
noq_django/backend/models.py
noq_django/backend/urls.py
noq_django/backend/views.py

- Added views for listing, viewing details, creating, updating, and deleting products.
- Ensured proper form handling and redirection in create and update views.
- Integrated product management functionality seamlessly with existing Django project.

Implemented CRUD operations for products in Django:

---

README.md
noq_django/backend/models.py
noq_django/backend/scripts/generate_data.py
noq_django/backend/test_booking.py
noq_django/noq_django/api/api_schemas.py

This change fixes issue with over booking. Following changes has been done
- Adds new test case to test for over booking
- Fixes booking code to pass the new test case
- Adds new states for booking based on the "UC boka sovplats"
- Updates generate_data to use State enum instead of magic values

Fix for bug #448

---

noq_django/noq_django/api/api.py
noq_django/noq_django/api/api_schemas.py
noq_django/noq_django/api/host_api.py

While I was fixing some issues with the frontend I noticed that the host api expects full Host object information from the client when updating room or creating a new room. This change will send this information to the client. Needs to be merged before frontend change for 393 is merged.

Updates data sent to host during login from host_id to Host object

---

Dockerfile
noq_django/manage.py
noq_django/noq_django/asgi.py
noq_django/noq_django/settings/common.py
noq_django/noq_django/settings/dev.py
noq_django/noq_django/settings/prod.py
noq_django/noq_django/wsgi.py
requirements.txt
scripts/run.sh

This change will make following changes in order for us to run build a production docker image.
- Add Dockerfile for building the image
- Create separates settings for production and development (selected by environmental variable)
- Adds requirements needed to use postgres database

Adds changes needed to build a production docker container

---

noq_django/noq_django/settings/common.py

Updates the BaseURL for django application

Emergency Fix to set correct BaseURL

---

noq_django/backend/scripts/delete_all_data.py
noq_django/backend/scripts/generate_data.py
noq_django/noq_django/api/api.py
noq_django/noq_django/api/host_api.py
noq_django/noq_django/settings/common.py

- Fixes delete all data and generate data scripts.
- Fixes wrong value returned for available places.
- Adds APIs to send incoming and outgoing bookings

Fixes and new APIs for Host overview page

---

noq_django/backend/scripts/generate_data.py
noq_django/rest_api/api/api.py
noq_django/rest_api/api/api_schemas.py
noq_django/rest_api/api/caseworker_api.py

This change adds possibility to log in as caseworker
changes:
- Adds new API for caseworker (returns just text for now)
- Updates generate_data script to create a caseworker in the database

Adds api for caseworker and group for caseworker to generate_data script

---

noq_django/rest_api/api/caseworker_api.py
noq_django/rest_api/api/test/test_caseworker_handle_booking_api.py

This PR will add following changes to the backend
- New api to show pending bookings for caseworker
- New api to accept booking for caseworker
- New api to decline booking for caseworker

516 skapa funktionalitet godknnneka bokning   handlggare

---

noq_django/rest_api/api/caseworker_api.py

This change:
- Removes unused API (/) (also this API returns wrong type of object, so it's either to remove or fix)
- Adds API setpending to allow undo functionality in the frontend (I forgot to add that in the first change).

Removes api for / and adds API for undo of accepted/declined bookings

---

noq_django/rest_api/api/caseworker_api.py
noq_django/rest_api/api/test/test_caseworker_handle_booking_api.py

- Det finns API för handläggare som skickar tillbaka listan av lediga platser i alla produkter i alla boenden handläggaren är ansvarig för.
- Det finns tester i backend för API

Skapa funktion se lediga platser boende #453,1 och #453,2

---

noq_django/rest_api/api/caseworker_api.py
noq_django/rest_api/api/test/test_caseworker_handle_booking_api.py

Right now backend doesn't return any pending requests for the caseworker. I needed to change the query to fetch the hosts for the caseworker to make it work.

Fixes empty pending requests list for caseworker

---

noq_django/backend/admin.py

- Adds new fields to ClientAdmin in admin.py

Adds fields for user and UNOKOD to the Admin form

---

noq_django/rest_api/api/host_api.py

Adds missing checkin and checkout APIs

Adds checkin and checkout APIs

---

noq_django/rest_api/api/host_api.py

Fixes bug shown in the video in demo channel. Bug report: 
BUG: incoming AP return pending and checked-in bookings
[#600](https://github.com/noQ-sweden/noq/issues/600)

Updates incoming and outgoing bookings API

---

noq_django/rest_api/api/api_schemas.py
noq_django/rest_api/api/host_api.py

The Booking time is not included in the information that backend sends to the client. This change adds booking_time to the sent information.

Updates BookingSchema

---

noq_django/rest_api/api/user_api.py

Backend for sending bookings to the guest, so he/she can check the status for a booking. No test cases done, will be done later, after the demo.

Adds API for user to fetch bookings

---

noq_django/backend/templates/daily_bookings.html
noq_django/backend/urls.py
noq_django/backend/views.py

daily booking overview 

---

noq_django/rest_api/api/api_schemas.py
noq_django/rest_api/api/caseworker_api.py

This patch makes following changes:
- Adds new API to fetch all bookings for all users during a time period
- Adds first name and last name to the UserShelterStayCountSchema

Update schema for user info

---

noq_django/rest_api/api/test/test_user_api.py
noq_django/rest_api/api/user_api.py

Her is the link to the ticket : https://github.com/orgs/noQ-sweden/projects/13/views/3?sliceBy%5Bvalue%5D=Mars&pane=issue&itemId=75850889&issue=noQ-sweden%7Cnoq%7C285

Add an api to delete a reserved booking and a test for that api 

---

noq_django/backend/urls.py
noq_django/backend/views.py

BUG: Proxy is not routing request directly when accessing react path

---

noq_django/rest_api/api/user_api.py

This change adds confirm API functionality for the guest. There is no story for this. I just realized we are missing this functionality while I was testing the app for demo.

Adds api endpoint for confirming the booking.

---

noq_django/rest_api/api/api.py

created 2 new api´s. for checking if user still has a active session and for the user to be able to logout and therefore deactivate the session. these 2 api´s helps with refresh problem. in the branch with the same name ( refresh-bug-#749 ) in frontend /LoginPage im using the self/auth to keep the user on the noq page after a refresh.

api for logout and a self authorization 

---

noq_django/rest_api/api/api_schemas.py
noq_django/rest_api/api/volunteer_api.py

Fix: Implement case-insensitive search for volunteers (#731)
- Updated `search_guest` endpoint to ensure case-insensitive search
- Normalized first name, last name, and UNO code before querying the database
- Fixed an issue where `None` UNO codes caused errors in search processing
- Improved debugging messages for better error tracking
- Added a new `SimplifiedClientSchema` in `api_schemas.py`
- Optimized `/guest/list` to include related fields for better performance

Backend/case insensitive search/#731

---

noq_django/rest_api/api/api_schemas.py
noq_django/rest_api/api/test/test_user_api.py
noq_django/rest_api/api/user_api.py

Needed to add support for specific future of getting all the available dates for specific selected host

Added new API for user to fetch all available product dates for host

---

noq_django/rest_api/api/api_schemas.py
noq_django/rest_api/api/test/test_user_api.py
noq_django/rest_api/api/user_api.py

Added a way to count how many places left there are for each host product for  `/api/user/available_host/${request.host.id}`

API changes to account for new design

---

noq_django/rest_api/api/api.py
noq_django/rest_api/api/api_schemas.py
noq_django/rest_api/api/test/test_user_api.py
noq_django/rest_api/api/test/test_volunteer_booking.py

API for the registration ticket [#822](https://github.com/noQ-sweden/noq/issues/822)

Registration API and testing case for each User and Volunteer group

---

noq_django/backend/doc/er_diagram.puml

This change updates the plantuml ER-diagram to make it complete.

Completes the er diagram

---

noq_django/rest_api/api/api.py
noq_django/rest_api/settings/common.py

Send email function and email backend implemented

---

noq_django/rest_api/api/admin_activities_api.py

Changed list_activities to display the volunteer names as well for the purpose of displaying them on the main activity card.

Volunteer name displays on main card

---

noq_django/rest_api/api/admin_activities_api.py
noq_django/rest_api/api/admin_api.py
noq_django/rest_api/api/admin_volunteer_api.py
noq_django/rest_api/api/api.py
noq_django/rest_api/api/api_schemas.py
noq_django/rest_api/api/caseworker_api.py
noq_django/rest_api/api/host_api.py
noq_django/rest_api/api/user_api.py
noq_django/rest_api/api/volunteer_activities_api.py
noq_django/rest_api/api/volunteer_api.py

Cleaning up stuff from the backend API files. 
All the imports and model calls that where greyed out where just removed this doesnt address any bugs or issues with logic.

Removed unused import, added all schemas to the global file
